version: "3"
services:
  vm-builder:
    build: ./
    privileged: true
    image: dcagatay/qemu-builder:latest
    volumes:
      - "./:/app"
    ports:
      - 5900-6000:5900-6000
    environment:
      PACKER_LOGS: "1"

        #  "0e -var-file vars/docker.hcl template-image.pkr.hcl"]
