apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: crossplane
      app.kubernetes.io/instance: uxp
      app.kubernetes.io/component: xgql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crossplane
        app.kubernetes.io/instance: uxp
        app.kubernetes.io/component: xgql
    spec:
      serviceAccountName: xgql
      containers:
      - name: xgql
        image: upbound/xgql:v0.1.5
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 300Mi
        ports:
          - name: https
            containerPort: 8443
            protocol: TCP
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
