---
# (string) Timezone for the servers
timezone: "Europe/Copenhagen"

# (list) Additional ssh public keys to add to the nodes
# ssh_authorized_keys:

fedora:
  packages:
    - dnf-plugin-system-upgrade
    - dnf-utils
    - hdparm
    - htop
    - ipvsadm
    - lm_sensors
    - nano
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-libselinux
    - python3-pyyaml
  packages_gpu:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - akmod-nvidia
    - xorg-x11-drv-nvidia-cuda

ubuntu:
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm-sensors
    - nano
    - nfs-common
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-yaml
  packages_gpu:
    - nvidia-headless-525-server
    - nvidia-container-runtime
