apiVersion: apps/v1
kind: Deployment
metadata:
  name: upbound-bootstrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: crossplane
      app.kubernetes.io/instance: uxp
      app.kubernetes.io/component: bootstrapper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crossplane
        app.kubernetes.io/instance: uxp
        app.kubernetes.io/component: bootstrapper
    spec:
      serviceAccountName: upbound-bootstrapper
      containers:
        - name: bootstrapper
          image: docker.io/upbound/uxp-bootstrapper:v1.10.3-up.1
          args:
            - start
            - --namespace
            - infrastructure
            - --controller
            - tls-secrets
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 256Mi
